# Generated by Django 3.1.3 on 2020-11-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='user', to='user.User', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='department',
            name='team',
            field=models.ManyToManyField(blank=True, default=None, related_name='team', to='team.Team', verbose_name='团队'),
        ),
    ]
