# Generated by Django 3.1.1 on 2020-12-02 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('skill_score', models.FloatField(max_length=1000, verbose_name='技能分数')),
                ('penalty_score', models.FloatField(max_length=1000, verbose_name='奖惩得分')),
                ('po_score', models.FloatField(max_length=1000, verbose_name='岗位分数')),
                ('total_score', models.FloatField(max_length=1000, verbose_name='总分')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('remark', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='员工姓名')),
            ],
            options={
                'verbose_name': '总计',
                'verbose_name_plural': '总计',
            },
        ),
        migrations.CreateModel(
            name='AddWorkload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worktime', models.CharField(max_length=1000, verbose_name='工作时长')),
                ('created_time', models.CharField(max_length=100, verbose_name='工作量所属日期')),
                ('remark', models.CharField(max_length=1000, verbose_name='备注')),
                ('updated_time', models.DateTimeField(blank=True, verbose_name='登记日期')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.department', verbose_name='指派分队')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.position', verbose_name='岗位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addworkload', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '工作量登记',
                'verbose_name_plural': '工作量登记',
            },
        ),
    ]
