# Generated by Django 3.1.3 on 2021-03-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='程度名称')),
            ],
            options={
                'verbose_name': '程度',
                'verbose_name_plural': '  程度',
            },
        ),
        migrations.CreateModel(
            name='LevelType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='程度类别名称')),
            ],
            options={
                'verbose_name': '程度类别',
                'verbose_name_plural': '  程度类别',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='岗位名称')),
                ('score', models.FloatField(verbose_name='岗位基础分数')),
                ('workload', models.FloatField(verbose_name='岗位基础工作量')),
                ('bonus', models.FloatField(verbose_name='岗位基础奖金')),
                ('man_hours', models.BooleanField(verbose_name='是否计算工时')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '    岗位',
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='岗位类别')),
            ],
            options={
                'verbose_name': '岗位类别',
                'verbose_name_plural': '   岗位类别',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖惩名称')),
                ('score', models.FloatField(verbose_name='奖惩基础分数')),
                ('workload', models.FloatField(verbose_name='奖惩基础工作量')),
                ('bonus', models.FloatField(verbose_name='奖惩基础奖金')),
            ],
            options={
                'verbose_name': '奖惩',
                'verbose_name_plural': '        奖惩',
            },
        ),
        migrations.CreateModel(
            name='RewardRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('workload', models.FloatField(blank=True, null=True, verbose_name='工作量')),
                ('bonus', models.FloatField(blank=True, null=True, verbose_name='奖金')),
                ('title', models.CharField(max_length=500, verbose_name='简述')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='详细情况')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '奖惩记录',
                'verbose_name_plural': '             奖惩记录',
            },
        ),
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖惩类别')),
            ],
            options={
                'verbose_name': '奖惩类别',
                'verbose_name_plural': '       奖惩类别',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('effect', models.CharField(max_length=100, verbose_name='作用于')),
                ('date_condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='时间条件')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='数量条件')),
                ('score', models.CharField(blank=True, max_length=100, null=True, verbose_name='分数权重')),
                ('workload', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作量权重')),
                ('bonus', models.CharField(blank=True, max_length=100, null=True, verbose_name='奖金权重')),
                ('man_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='工时权重')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': ' 规则',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='班次')),
                ('score', models.FloatField(verbose_name='班次基础分数')),
                ('workload', models.FloatField(verbose_name='班次基础工作量')),
                ('bonus', models.FloatField(verbose_name='班次基础奖金')),
            ],
            options={
                'verbose_name': '班次',
                'verbose_name_plural': '          班次',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('score', models.FloatField(verbose_name='技能基础分数')),
                ('workload', models.FloatField(verbose_name='技能基础工作量')),
                ('bonus', models.FloatField(verbose_name='技能基础奖金')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '      技能',
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='技能类别')),
            ],
            options={
                'verbose_name': '技能类别',
                'verbose_name_plural': '     技能类别',
            },
        ),
        migrations.CreateModel(
            name='WorkloadRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('working_time', models.FloatField(verbose_name='工作时长')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('workload', models.FloatField(blank=True, null=True, verbose_name='工作量')),
                ('bonus', models.FloatField(blank=True, null=True, verbose_name='奖金')),
                ('man_hours', models.FloatField(blank=True, null=True, verbose_name='奖金')),
                ('remark', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('verified', models.BooleanField(default=False, verbose_name='审核状态')),
                ('verified_datetime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_team', to='team.team', verbose_name='指派')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.level', verbose_name='程度')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.position', verbose_name='岗位')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.shift', verbose_name='班次')),
                ('team', models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组')),
            ],
            options={
                'verbose_name': '工作量记录',
                'verbose_name_plural': '              工作量记录',
                'ordering': ['-created_datetime'],
            },
        ),
    ]
