# Generated by Django 3.1.1 on 2020-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addworkload',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登记日期'),
        ),
    ]
