# Generated by Django 3.1.3 on 2021-04-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_user', to='user.user', verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='workloadrecord',
            name='verified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_user', to='user.user', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='shift',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.rule', verbose_name='规则'),
        ),
        migrations.AddField(
            model_name='shift',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='rule',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='rewardtype',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.level', verbose_name='程度'),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.reward', verbose_name='奖惩'),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_user', to='user.user', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='reward',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.rule', verbose_name='规则'),
        ),
        migrations.AddField(
            model_name='reward',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='reward',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.rewardtype', verbose_name='奖惩类别'),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='position',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.rule', verbose_name='规则'),
        ),
        migrations.AddField(
            model_name='position',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.positiontype', verbose_name='岗位类别'),
        ),
        migrations.AddField(
            model_name='leveltype',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='level',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.rule', verbose_name='规则'),
        ),
        migrations.AddField(
            model_name='level',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='level',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.leveltype', verbose_name='程度类别'),
        ),
        migrations.CreateModel(
            name='RewardSummary',
            fields=[
            ],
            options={
                'verbose_name': '奖惩记录',
                'verbose_name_plural': '             奖惩统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('performance.rewardrecord',),
        ),
        migrations.CreateModel(
            name='WorkloadSummary',
            fields=[
            ],
            options={
                'verbose_name': '工作量记录',
                'verbose_name_plural': '              工作量统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('performance.workloadrecord',),
        ),
    ]
