# Generated by Django 3.1.3 on 2021-03-31 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20210330_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.rule', verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='rewardrecord',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.level', verbose_name='程度'),
        ),
        migrations.AlterField(
            model_name='workloadrecord',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.level', verbose_name='程度'),
        ),
    ]
