# Generated by Django 3.1 on 2020-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20, verbose_name='上次登录ip'),
        ),
    ]
